### PR TITLE
gsim and glim for new skin

### PR DESCRIPTION
**Pull request by nikIntrasoft**
GLIM and GSIM features for new Skin

### CODE REVIEW

**Comment by Ippezrobert** [comment]
@nikIntrasoft @tarzan0820 Error - Cannot read property 'productName' of undefined at ViewGLIMaccountController.js line 114. Also you cannot make GSIM Deposit, please see issue https://github.com/iDTLabssl/fineract/issues/30

**Comment by nikIntrasoft** [comment]
@Ippezrobert  Both the issues you have reported are not present in the latest PR. 
Could you please clone the latest PR and retry.

**Comment by Ippezrobert** [comment]
@nikIntrasoft , Still after cloning the latest PR from your repository at https://github.com/nikIntrasoft/incubator-fineract/tree/glimsprod it failed then i tried from https://github.com/iDTLabssl/fineract/tree/develop still its failing to make deposit to GSIM Account.

POST https://localhost:8443/fineract-provider/api/v1/savingsaccounts/1/transactions?command=gsimDeposit 500 (Internal Server Error).

Could you please send me a single PR to https://github.com/Ippezrobert/incubator-fineract develop and UI to https://github.com/Ippezrobert/community-app. I need this Feature for managing VSLA Groups, hope it will help me.

**Comment by nikpawar89** [comment]
@Ippezrobert  please use develop branch of both front end and back end of idtlabssl.
My branch doesn't have some migraton sql and might cause you some issue.
 Let me give you the steps:
1)clone idtlabssl/fineract -develop branch
2) clone idtlabssl/community-app - develop branch

make a fresh schema.. do not use the same schema.
This has worked for me and others as well. If you have still have issues lets have a call.

**Comment by Ippezrobert** [comment]
@nikIntrasoft , I have already cloned https://github.com/apache/fineract and https://github.com/openMF/community-app and  made some custom enhancements so how do I just pick those PRs to my local branch with the latest changes from idtlabssl???

i used 
git pull https://idtlabssl/fineract develop
git https://idtlabssl/community-app develop 

then resolved some conflicts and build and deployed but was still facing issues especially making deposit to GSIM account

**Comment by nikIntrasoft** [comment]
Oh you are just using difference..
Can you send me internal server error stack trace..
Is it missing column error?

**Comment by Ippezrobert** [comment]
@nikIntrasoft, it's now okay but one thing
Closing of GSIM Account throws this error in web browser console

TypeError: Cannot read property 'accountBalance' of undefined
    at GSIMAccountActionsController.js:151
    at angular-resource.js:554
    at wrappedCallback (angular.js:10930)
    at angular.js:11016
    at Scope.$eval (angular.js:11936)
    at Scope.$digest (angular.js:11762)
    at Scope.$apply (angular.js:12042)
    at done (angular.js:7824)
    at completeRequest (angular.js:8007)
    at XMLHttpRequest.xhr.onreadystatechange (angular.js:7963)

And also on the view group page in this line
<td class="pointer" data-ng-click="routeToGSIMAccount(gsimAccount.accountNumber)">{{gsimAccount.parentBalance}}</td>

The parentBalance should be the summation of all childBalance but it's taking the value of the amounts deposited through gsimDeposit command, but what if deposits are made to individual accounts separately through savingaccount/14/deposit assuming saving account 14 belongs to a client in a GSIM category.

Or restrict individual deppsit and withdrawal for GSIM Accounts on client/child basis in community-app.

Is it possible to make withdrawal in GSIM? Am not seeing it in the UI from viewgsimaccount.

**Comment by nikIntrasoft** [comment]
@Ippezrobert.. even if you do a separate deposit to child account separately.. there is a provision in backend which identifies it as one of the child gsim account and updates the parent balance

**Comment by Ippezrobert** [comment]
@nikIntrasoft , how about the issue i raised above about TypeError: Cannot read property 'accountBalance' of undefined
at GSIMAccountActionsController.js:151.And also i don't see withdrawal button.

**Comment by Ippezrobert** [comment]
@nikIntrasoft, Also in /viewglimaccount page there is an error below
angular.js:9400 TypeError: Cannot read property 'productName' of undefined
    at ViewGLIMaccountController.js:114
    at angular-resource.js:554
    at wrappedCallback (angular.js:10930)
    at angular.js:11016
    at Scope.$eval (angular.js:11936)
    at Scope.$digest (angular.js:11762)
    at Scope.$apply (angular.js:12042)
    at done (angular.js:7824)
    at completeRequest (angular.js:8007)
    at XMLHttpRequest.xhr.onreadystatechange (angular.js:7963)

image

**Comment by nikpawar89** [comment]
@Ippezrobert  view glim works absolutely fine
image

**Comment by Ippezrobert** [comment]
@nikIntrasoft, could you send me the production/compiled files for community-app and i test using my backend. my email is ippezrobert@gmail.com

**Comment by nikpawar89** [comment]
@Ippezrobert  We did not plan bulk withdraw, so there is no withdraw button under gsim.
I am trying to compress the files but i think before that let try sending you a pr.

**Comment by Ippezrobert** [comment]
@nikIntrasoft , Hi did you manage to compress and send? You also talked about sending me PR, to which repository did you send? Thanks

**Pull request merged**
